### ISSUE TITLE
Remove eslint-plugin-prettier

### ISSUE THREAD

**Issue by jasonschroeder-sfdc** [forcedotcom/eslint-config-salesforce#19]
Can we discuss removing [eslint-plugin-prettier](https://www.npmjs.com/package/eslint-plugin-prettier) ? 

It's [not recommended by the prettier team](https://prettier.io/docs/en/integrating-with-linters.html#notes), and I find it to run duplicate tools when prettier is configured separately.

Please let me know, I am happy to open a PR to remove it. Thank you!

**Comment by mshanemc** [comment]
go for it!
